### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by fritzsedlazeck** [mlin/spVCF#8]
Hi,
this looks very interesting. I would have some naive questions:

What is the compression rate (e.g. over 1000 genomes)?
How long does it take to compress it?
How long does it take to decompress it or is it usable with other methods?

Thanks
Fritz

**Comment by mlin** [comment]
Hi @fritzsedlazeck 

I'm currently compiling a report on the compression achieved by this prototype, using the same cohorts studied in our [GLnexus preprint](https://www.biorxiv.org/content/early/2018/06/11/343970). It's looking very promising but I'm going to take a few more days to double-check things. A couple comments since you mentioned 1000GP, 1) spVCF's effectiveness seems to kick in with *N*>10K, I think it's going to be meh with *N*=2504; 2) the 1000GP joint VCF files we all know and love only report the hard-called genotypes, so for example there's no straightforward way to know the read depth supporting each call. This is already very run-length compressible by bgzip, so spVCF will only help a little; it's really taking aim at project VCF files reporting an array of QC fields with each genotype call.

The encoder seems to be e a few times slower than bgzip right now, i.e. usable albeit not great. I have a plan in #7 to multithread the encoder and eventually I would imagine GLnexus and similar tools emitting a sparse format directly. The decoding is pretty fast and can be made faster, as there's still some unnecessary memory copying going on in the C++ code.

**Comment by fritzsedlazeck** [comment]
Awesome looking forward to trying it out.
Thanks
Fritz

**Comment by mlin** [comment]
@fritzsedlazeck check out https://github.com/mlin/spVCF/blob/master/doc/compression_results.md I welcome your input!
